# Base Configuration
baseurl = "/"
languageCode = "de-ch"
languageLang = "de"
title = "3dimensional: Innenarchitektur, Gestaltung und dreidimensionale Kommunikation"
enableRobotsTXT = "true"

# Archetypes Management
MetaDataFormat = "yaml"

# taxonomies
[taxonomies]
#     tag = "tags"
#     category = "categories"
#     author = "authors"

[outputs]
  section = ["HTML", "JSON"]
