# Base Configuration
baseurl = "/"
languageCode = "de-ch"
languageLang = "de"
title = "3dimensional: Innenarchitektur, Gestaltung und dreidimensionale Kommunikation"

# Parameter Management
[params]
    appColor = "#B6C229"
    appTitle = "3dimensional: Innenarchitektur, Gestaltung und dreidimensionale Kommunikation"
    appDescription = "3dimensional entwickelt Lösungen, die exakt auf Ihre Bedürfnisse zugeschnitten sind. Damit können wir Ihnen ein Optimum an Leistungen zu realistischen Preisen garantieren. In jedem unserer drei Segmente arbeiten wir als Generalunternehmer oder aber nur für einzelne Teilbereiche Ihres Projektes. Je nach Ihren Anforderungen und Wünschen. Durch unser weitreichendes und flexibles Netzwerk aus eingespielten Fachexperten können wir Aufträge unterschiedlicher Grösse, schnell, effizient und professionell umsetzen."
    appKeywords = "3dimensional, 3 dimensional, Innenarchitektur, Gestltung, Innenräume, Ladenbau, dreidimensional Kommunikation, 3D"
    appSitemapUrl = "https://www.3dimensional.ch"
    appPublisher = "3dimensional AG"
    appTitleShort = "3dimensional"
    appImage = "images/uploads/3dimensional-hero-1.jpg"
    appGoogleVerification = "123xyz-google-hash"
    referenceActivities = [ "Shopdesign", "Bürodesign", "Rendering", "Ausstellungsgestaltung", "Schaufenstergestaltung", "Eventgestaltung", "Messegestaltung", "Signaletik", "Display", "Point of Sale" ]
    referenceCompetences = [ "Idee", "Planung", "Ausführung" ]

# URL Management
[permalinks]
  posts = "/posts/:title/"

# Archetypes Management
MetaDataFormat = "yaml"

# taxonomies
[taxonomies]
#     tag = "tags"
#     category = "categories"
#     author = "authors"
