backend:
  name: github
  repo: ditoy/3dimensional-website-2018 # Path to your Github repository
  branch: dev # Branch to update (master by default)

display_url: https://www.3dimensional.ch

media_folder: "site/static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit

  - name: "page"
    label: "Seiten"
    folder: "site/content"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Titel", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publikationsdatum", name: "date", widget: "datetime"}
      - {label: "Seiteninhalt", name: "body", widget: "markdown"}

  - name: "project"
    label: "Projekte"
    folder: "site/content/projects"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publikationsdatum", name: "date", widget: "datetime" }
      - { label: "Aktiv", name: "active", widget: "boolean", default: true, required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "Jahr", name: "Year", widget: "date", format: "YYYY", required: false }
      - { label: "Referenz-URL", name: "reference", widget: "string", required: false }
      - { label: "Thumbnail Teaser-Bild", name: "imagethumb", widget: "file" }
      - { label: "Teaser-Bild", name: "imagefull", widget: "file" }
      - { label: "Teaser-Text", name: "teaser", widget: "text" }
      - { label: "Seiteninhalt", name: "body", widget: "markdown", required: false }

  - name: "team"
    label: "Mitarbeiter"
    folder: "site/content/team"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Vor- & Nachname", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publikationsdatum", name: "date", widget: "datetime" }
      - { label: "Rangfolge", name: "position", widget: "number" }
      - { label: "Funktion", name: "function", widget: "string", tagname: "h3" }
      - { label: "Aktiv", name: "active", widget: "boolean", default: true, required: false }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "E-Mail", name: "email", widget: "string", required: false }
      - { label: "Telefon", name: "phone", widget: "string", required: false }
      - { label: "Instagram (Komma getrennt, ohne @)", name: "instagram", widget: "list", required: false }
      - { label: "Website (Komma getrennt, ganze URL)", name: "web", widget: "list", required: false }
      - { label: "Thumbnail Bild (600x600 px)", name: "imagethumb", widget: "file" }
      - { label: "Bild (1200x760 px)", name: "image", widget: "file" }
      - { label: "Seiteninhalt", name: "body", widget: "markdown", required: false }
