backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

display_url: https://www.3dimensional.ch

media_folder: "site/static/images/uploads" # Folder where user uploaded files should go
public_folder: "./images/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: 51fe52694febf733ab27

collections: # A list of collections the CMS should be able to edit

  - label: "Konfiguration"
    name: "configuration"
    files:
      - label: "Globale Einstellungen"
        name: "configuration_index"
        file: "site/content/configuration/config.md"
        fields:
          - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
          - { label: "appColor", name: "appColor", widget: "string", tagname: "p" }
          - { label: "appTitle", name: "appTitle", widget: "string", tagname: "p" }
          - { label: "appTitleShort", name: "appTitleShort", widget: "string", tagname: "p" }
          - { label: "appPublisher", name: "appPublisher", widget: "string", tagname: "p" }
          - { label: "appDescription", name: "appDescription", widget: "string", tagname: "p" }
          - { label: "appKeywords", name: "appKeywords", widget: "string", tagname: "p" }
          - { label: "appImage", name: "appImage", widget: "string", tagname: "p" }
          - { label: "appSitemapUrl", name: "appSitemapUrl", widget: "string", tagname: "p" }
          - { label: "appGoogleVerification", name: "appGoogleVerification", widget: "string", tagname: "p" }
          - { label: "referenceCompetences", name: "referenceCompetences", widget: "list", tagname: "p" }
      - label: "Landing Page Einstellungen"
        name: "configuration_slides"
        file: "site/content/configuration/landingpage.md"
        fields:
        - { label: "Slide 1 Bild", name: "slide1_image", widget: "file" }
        - { label: "Slide 1 Claim", name: "slide1_claim", widget: "string" }
        - { label: "Slide 1 Textfarbe", name: "slide1_color", widget: "select", options: ["black", "white"] }
        - { label: "Slide 2 Bild", name: "slide2_image", widget: "file" }
        - { label: "Slide 2 Claim", name: "slide2_claim", widget: "string" }
        - { label: "Slide 2 Textfarbe", name: "slide2_color", widget: "select", options: ["black", "white"] }
        - { label: "Slide 3 Bild", name: "slide3_image", widget: "file" }
        - { label: "Slide 3 Claim", name: "slide3_claim", widget: "string" }
        - { label: "Slide 3 Textfarbe", name: "slide3_color", widget: "select", options: ["black", "white"] }
        - { label: "Slide 4 Bild", name: "slide4_image", widget: "file" }
        - { label: "Slide 4 Claim", name: "slide4_claim", widget: "string" }
        - { label: "Slide 4 Textfarbe", name: "slide4_color", widget: "select", options: ["black", "white"] }
        - { label: "Slide 5 Bild", name: "slide5_image", widget: "file" }
        - { label: "Slide 5 Claim", name: "slide5_claim", widget: "string" }
        - { label: "Slide 5 Textfarbe", name: "slide5_color", widget: "select", options: ["black", "white"] }
        - { label: "Slide 6 Bild", name: "slide6_image", widget: "file" }
        - { label: "Slide 6 Claim", name: "slide6_claim", widget: "string" }
        - { label: "Slide 6 Textfarbe", name: "slide6_color", widget: "select", options: ["black", "white"] }
        - { label: "Quote 1 Bild", name: "quote1_image", widget: "file" }
        - { label: "Quote 1", name: "quote1", widget: "string", tagname: "cite" }
        - { label: "Quote 2 Bild", name: "quote2_image", widget: "file" }
        - { label: "Quote 2", name: "quote2", widget: "string", tagname: "cite" }
        - { label: "Quote 3 Bild", name: "quote3_image", widget: "file" }
        - { label: "Quote 3", name: "quote3", widget: "string", tagname: "cite" }
      - label: "Footer Einstellungen"
        name: "configuration_footer"
        file: "site/content/configuration/footer.md"
        fields:
        - { label: "Footer Spalte 1", name: "column_1", widget: "markdown", tagname: "div" }
        - { label: "Footer Spalte 2", name: "column_2", widget: "markdown", tagname: "div" }
        - { label: "Footer Spalte 3", name: "column_3", widget: "markdown", tagname: "div" }

  - label: "Index-Seiten"
    name: "page_index"
    files:
      - label: "Index / Landingpage"
        name: "index"
        file: "site/content/_index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
          - { label: "Publikationsdatum", name: "date", widget: "datetime" }
          - { label: "Seiteninhalt", name: "body", widget: "markdown" }
      - label: "Index Projekte"
        name: "projects_index"
        file: "site/content/projects/_index.md"
        fields:
          - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
          - { label: "Publikationsdatum", name: "date", widget: "datetime" }
          - { label: "Seiteninhalt", name: "body", widget: "markdown" }
      - label: "Index Team"
        name: "team_index"
        file: "site/content/team/_index.md"
        fields:
        - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - { label: "Publikationsdatum", name: "date", widget: "datetime" }
        - { label: "Seiteninhalt", name: "body", widget: "markdown" }
      - label: "Index Jobs"
        name: "jobs_index"
        file: "site/content/jobs/_index.md"
        fields:
        - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
        - { label: "Publikationsdatum", name: "date", widget: "datetime" }
        - { label: "offene Stellen?", name: "hasJobs", widget: "boolean" }
        - { label: "Text mit offenen Stellen", name: "textJobs", widget: "markdown" }
        - { label: "Text ohne Stellen", name: "textNoJobs", widget: "markdown" }
  - name: "page"
    label: "Weitere Seiten"
    folder: "site/content"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publikationsdatum", name: "date", widget: "datetime" }
      - { label: "Seiteninhalt", name: "body", widget: "markdown" }

  - name: "project"
    label: "Projekte"
    folder: "site/content/projects"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Titel", name: "title", widget: "string", tagname: "h1" }
      - { label: "Publikationsdatum", name: "date", widget: "datetime" }
      - { label: "Rangfolge", name: "position", widget: "number", default: 20 }
      - { label: "Nicht auf Website publizieren", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "Jahr", name: "Year", widget: "date", format: "YYYY", required: false }
      - { label: "Referenz-URL", name: "reference", widget: "string", required: false }
      - { label: "Design", name: "concept", widget: "boolean", default: false, required: false }
      - { label: "Planung", name: "planning", widget: "boolean", default: false, required: false }
      - { label: "Produktion", name: "implementation", widget: "boolean", default: false, required: false }
      - label: "Aufgabenbereiche"
        name: "activities"
        widget: "list"
        field: {label: "Aufgabenbereich", widget: "select", options: ['Ausstellungsgestaltung', ‘Beschriftung’, 'Bürodesign', 'Display', 'Eventgestaltung', 'Innenarchitektur', 'Leuchtendesign', 'Leuchtwerbung', 'Messegestaltung', 'Point-of-Information', 'Point-of-Sale', 'Promotionsfläche', 'Rendering', 'Schaufenstergestaltung', 'Shopdesign', 'Signaletik', 'Wandgestaltung']}
        required: false
      - { label: "Teaser-Bild", name: "image", widget: "image" }
      - { label: "Teaser-Bild Titel / Alt", name: "imageAlt", widget: "string", required: false }
      - { label: "Teaser-Text", name: "teaser", widget: "text" }
      - label: "Projektbilder"
        name: "projectpictures"
        widget: "list"
        field: {label: "Bild", widget: "image", default: "", required: false }
        required: false
      - { label: "Seiteninhalt", name: "body", widget: "markdown", required: false }

  - name: "team"
    label: "Mitarbeiter"
    folder: "site/content/team"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Publikationsdatum", name: "date", widget: "datetime" }
      - { label: "Rangfolge", name: "position", widget: "number", default: 20 }
      - { label: "Nicht auf Website publizieren", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "Von Google-Suche ausschliessen", name: "robotsExclude", widget: "boolean", default: false, required: false }
      - { label: "Vor- & Nachname", name: "title", widget: "string", tagname: "h1" }
      - { label: "Funktion", name: "function", widget: "string", tagname: "h3" }
      - { label: "kurzes Zitat", name: "quote", widget: "string", tagname: "h4", required: false }
      - { label: "E-Mail", name: "email", widget: "string", required: false }
      - { label: "Telefon", name: "phone", widget: "string", required: false }
      - { label: "Mitarbeiter-Bild", name: "image", widget: "file" }
      - { label: "Seiteninhalt", name: "body", widget: "markdown", required: false }

  - name: "job"
    label: "Jobs"
    folder: "site/content/jobs"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Nicht auf Website publizieren", name: "draft", widget: "boolean", default: true, required: false }
      - { label: "Publikationsdatum", name: "date", widget: "datetime" }
      - { label: "Stellenbezeichnung", name: "title", widget: "string", tagname: "h1" }
      - { label: "Seiteninhalt", name: "body", widget: "markdown" }

  - name: "customer"
    label: "Kundenliste"
    folder: "site/content/customers"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
    - { label: "Kunde", name: "title", widget: "string", tagname: "h1" }
    - { label: "Nicht auf Website publizieren", name: "draft", widget: "boolean", default: true, required: false }
